"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { ArrowLeft, Moon, Sun, ShieldCheck } from "lucide-react";
import { AscendLogo } from "@/components/ascend-logo";

const sections = [
  {
    title: "1. Information We Collect",
    body: "We collect information you provide directly (such as the account email and password you use to sign in, and any readiness, performance, or contact data entered into the Platform), information generated by your use of the Platform (such as audit logs of views, edits, and exports), and minimal device information needed to maintain session security.",
  },
  {
    title: "2. How We Use Information",
    body: "We use the information we collect to authenticate users, deliver role-scoped workspaces, surface readiness signals to authorized personnel, maintain audit trails for compliance, and protect the security and integrity of the Platform. We do not use personal information for advertising or marketing.",
  },
  {
    title: "3. Population Scope & Privacy States",
    body: "Every record carries a population scope (Individual, Assigned Caseload, Cohort, Unit, or Organization) and a privacy state (such as Opted In, Consent Withdrawn, Authorization Required, Access Expired, or Access Denied). Records are only visible to users whose role and scope permit access, and only while the privacy state allows it.",
  },
  {
    title: "4. Consent",
    body: "Where a workflow requires consent from the tracked person, the record will display a Consent Required state until consent is documented. Consent can be withdrawn at any time by contacting your administrator or following the in-product control; withdrawn consent transitions the record to Consent Withdrawn and blocks further viewing.",
  },
  {
    title: "5. Data Sharing",
    body: "We do not sell personal information. Information is shared only with authorized personnel within the user's population scope, with the tracked person upon request, with administrators performing their duties, or as required by applicable law or policy.",
  },
  {
    title: "6. Data Retention",
    body: "We retain records and audit logs for the period required by applicable policy, after which they are archived or destroyed in accordance with the records control schedule. Deactivated accounts lose access immediately; their historical records are retained per the same schedule.",
  },
  {
    title: "7. Security",
    body: "Ascend uses transport encryption, scoped role-based access, auditable workflows, and CUI/OPSEC handling banners to protect information. No system is perfectly secure; if you believe your account or data has been compromised, contact your administrator immediately.",
  },
  {
    title: "8. Your Choices & Rights",
    body: "Depending on your role, you may request a copy of the personal information associated with your account, request corrections, or withdraw consent for workflows that require it. Submit requests through the Contact section on our home page or to your administrator.",
  },
  {
    title: "9. Children's Privacy",
    body: "Ascend is an operational tool for authorized personnel and is not directed to children. We do not knowingly collect personal information from children.",
  },
  {
    title: "10. Contact Us",
    body: "Questions about this Privacy Policy can be sent through the Contact section on our home page or emailed to privacy@ascend.mil.",
  },
];

export default function PrivacyPage() {
  const [theme, setTheme] = useState<"light" | "dark">("light");

  useEffect(() => {
    const savedTheme = localStorage.getItem("ascend_admin_theme") as "light" | "dark" | null;
    const initialTheme: "light" | "dark" = savedTheme ?? "light";
    document.documentElement.classList.toggle("dark", initialTheme === "dark");
    const timer = setTimeout(() => setTheme(initialTheme), 0);
    return () => clearTimeout(timer);
  }, []);

  const toggleTheme = () => {
    const newTheme = theme === "light" ? "dark" : "light";
    setTheme(newTheme);
    localStorage.setItem("ascend_admin_theme", newTheme);
    document.documentElement.classList.toggle("dark", newTheme === "dark");
  };

  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground font-sans antialiased">
      {/* HEADER */}
      <header className="sticky top-0 z-30 w-full border-b border-border/60 bg-background/70 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-6 md:px-10">
          <Link href="/" className="flex items-center gap-2.5">
            <AscendLogo width={24} height={24} showDetails={false} />
            <span className="text-base font-semibold tracking-tight text-foreground">
              Ascend
            </span>
          </Link>

          <div className="flex items-center gap-2">
            <button
              onClick={toggleTheme}
              className="flex size-9 items-center justify-center rounded-full border border-border bg-surface text-foreground transition-all duration-200 hover:border-border-strong hover:bg-surface-muted cursor-pointer"
              title={theme === "light" ? "Switch to dark" : "Switch to light"}
              type="button"
            >
              {theme === "light" ? <Moon className="size-4" /> : <Sun className="size-4" />}
            </button>
            <Link
              href="/"
              className="inline-flex items-center gap-1.5 rounded-full border border-border bg-surface px-4 py-2 text-sm font-semibold text-foreground transition-all duration-200 hover:border-border-strong hover:bg-surface-muted"
            >
              <ArrowLeft className="size-3.5" />
              Back
            </Link>
          </div>
        </div>
      </header>

      {/* CONTENT */}
      <main className="flex-1">
        <div className="mx-auto max-w-3xl px-6 py-16 md:px-10 md:py-24">
          <div className="flex items-center gap-3">
            <div className="flex size-10 items-center justify-center rounded-xl border border-border bg-surface text-[var(--brand-color)]">
              <ShieldCheck className="size-5" />
            </div>
            <p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[var(--brand-color)]">
              Legal
            </p>
          </div>

          <h1 className="mt-6 text-4xl font-semibold tracking-[-0.02em] text-balance text-foreground md:text-5xl">
            Privacy Policy
          </h1>

          <p className="mt-3 text-xs font-medium uppercase tracking-wider text-muted">
            Last updated · September 6, 2026
          </p>

          <p className="mt-10 text-base leading-relaxed text-muted">
            Ascend handles personal information only to the extent necessary to
            support authorized readiness workflows. This Privacy Policy describes
            what we collect, how we use it, and the choices you have.
          </p>

          <div className="mt-12 space-y-10 border-t border-border pt-10">
            {sections.map((section) => (
              <section key={section.title}>
                <h2 className="text-lg font-semibold tracking-tight text-foreground">
                  {section.title}
                </h2>
                <p className="mt-3 text-[15px] leading-relaxed text-muted">
                  {section.body}
                </p>
              </section>
            ))}
          </div>
        </div>
      </main>

      {/* FOOTER */}
      <footer className="border-t border-border/60">
        <div className="mx-auto flex max-w-5xl flex-col items-start justify-between gap-3 px-6 py-8 text-xs text-muted md:flex-row md:items-center md:px-10">
          <p>© {new Date().getFullYear()} Ascend Program Office · All rights reserved.</p>
          <div className="flex items-center gap-5 font-medium">
            <Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link>
            <Link href="/privacy" className="text-foreground">Privacy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
